name: Run Gradle
on: 
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: gradle/wrapper-validation-action@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
        wrapper-cache-enabled: true
        dependencies-cache-enabled : true
        configuration-cache-enabled : true
    - uses: mikepenz/action-junit-report@v1
      name: Publish Test Report
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}


#  publish-test-results:
#    name: "Publish Unit Tests Results"
#    needs: gradle
#    runs-on: ubuntu-latest
#    # the build-and-test job might be skipped, we don't need to run this job then
#    if: success() || failure()
#
#    steps:
#      - name: Download Artifacts
#        uses: actions/download-artifact@v2
#        with:
#          path: artifacts
#
#      - name: Publish Unit Test Results
#        uses: EnricoMi/publish-unit-test-result-action@v1.6
#        with:
#          check_name: Unit Test Results
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          files: pytest.xml